{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMEJRlHBOWTcS1G2vD54hob"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["<h1><b>Excepciones</b></h2> </p>\n","\n","Las excepciones son utilizadas para el manejo de errores. Cuando se trata de errores, en cuento menos tengamos mejor, sin embargo es cierto también que estos son inevitables, siempre estamos propensos a encontrar un error o \"bug\" dentro de nuestros programas.\n","\n","Conociendo esto y tomando en cuenta que los errores son parte del día a día del desarrollador, para evitar que nuestra aplicación se cierre al ocurrir un error, o que la experiencia del usuario en nuestro sistema sea mala, vamos a hacer uso de las excepciones"],"metadata":{"id":"ZiTX8pYuYTXZ"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"5LkEKwGsYQ-h"},"outputs":[],"source":["#Sintaxis\n","try:\n","  run this code\n","except:\n","  Execute this code when there is an error\n","else:\n","  Whitout errors? Run this code.\n","finally:\n","  Always run this code."]},{"cell_type":"markdown","source":["<b>Ejemplo del error</b>"],"metadata":{"id":"t4cLHGM7gxTi"}},{"cell_type":"code","source":["numberOne = 5\n","numberTwo = 1\n","numberTwo = '1'"],"metadata":{"id":"qcHiDCBld9Pk","executionInfo":{"status":"ok","timestamp":1676295638672,"user_tz":360,"elapsed":8,"user":{"displayName":"Erick Galindo","userId":"17230836761258543942"}}},"execution_count":1,"outputs":[]},{"cell_type":"code","source":["print(numberOne + numberTwo)\n","#El tener un error directo en consola significa que nuestro programa ha muerto"],"metadata":{"id":"QInHvwJ2bI_z","colab":{"base_uri":"https://localhost:8080/","height":181},"executionInfo":{"status":"error","timestamp":1676295771784,"user_tz":360,"elapsed":187,"user":{"displayName":"Erick Galindo","userId":"17230836761258543942"}},"outputId":"bbfe8cca-51d5-4d58-a10e-896b051c6ab4"},"execution_count":4,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-ea4b39916cb7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumberOne\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mnumberTwo\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;31m#El tener un error directo en consola significa que nuestro programa ha muerto\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}]},{"cell_type":"markdown","source":["<b>Aplicando try - except</b>"],"metadata":{"id":"_dy9YjcrgxEY"}},{"cell_type":"code","source":["#Try - Except\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except: \n","  #Se ejecuta si se produce una excepcion\n","  print('Se ha producido un error')"],"metadata":{"id":"8Acl4LS0d2qs"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<b>Aplicando Try - Except - Else</b>"],"metadata":{"id":"GQ1s7JgzhCEx"}},{"cell_type":"code","source":["#Try - Except - Else (Opcional)\n","numberOne = 1\n","numberTwo = 2\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except: \n","  print('Se ha producido un error')\n","else:\n","  #Se ejecuta si no se produce ninguna excepción\n","  print('La ejecución continúa correctamente')"],"metadata":{"id":"seHgPxJgexf5"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<b>Aplicando Try - Except - Else - Finally </b>"],"metadata":{"id":"28F3CasOhHYi"}},{"cell_type":"code","source":["#Try - Except - Else (Opcional) - Finally (Opcional)\n","numberOne = 1\n","#numberTwo = 2\n","numberTwo = '2'\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except: \n","  print('Se ha producido un error')\n","else:\n","  print('La ejecución continúa correctamente')\n","finally:\n","  #Esto siempre se ejecuta \n","  print('La ejecución sigue')"],"metadata":{"id":"gKUd7QtJf1D-"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["<b>Analizando tipos de errores</b>"],"metadata":{"id":"TvRQeSoohNOS"}},{"cell_type":"code","source":["numberOne = 5\n","numberTwo = 1\n","numberTwo = '1'\n","\n","print(numberOne + numberTwo)"],"metadata":{"id":"YG2LJHJ4hQDy"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except TypeError: \n","  #Se ejecuta unicamente si el error es en el tipo de dato\n","  print('Se ha producido un error')"],"metadata":{"id":"D-Y2vDddhaHd"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["#Solucionado el error\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except TypeError: \n","  print('Hubo un error')\n","  print('Pero ya lo arreglé')\n","  fixOne = int(numberOne)\n","  fixTwo = int(numberTwo)\n","  print(fixOne + fixTwo)"],"metadata":{"id":"11aDEKj2hZ4L"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["#Hay muchos tipos de error\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except ValueError: \n","  print('Hubo un error')"],"metadata":{"id":"78NUyvioi21h","colab":{"base_uri":"https://localhost:8080/","height":232},"executionInfo":{"status":"error","timestamp":1676296932741,"user_tz":360,"elapsed":496,"user":{"displayName":"Erick Galindo","userId":"17230836761258543942"}},"outputId":"42048225-991e-4327-eb33-d57f754dfb60"},"execution_count":18,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-18-dec735cd56e8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m#Hay muchos tipos de error\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnumberOne\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mnumberTwo\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'No hay ningun error'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}]},{"cell_type":"code","source":["try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except TypeError: \n","  print('Se ha producido un TypeError')\n","except ValueError:\n","  print('Hubo un error de valor')"],"metadata":{"id":"dVgZ8wPgjWAA"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Lo normal y correcto es que nosotros sepamos qué se está ejecutando en cada sección específica de nuestro código. Así podemos intuir el tipo de error que se pudiera cometer y solucionarlo con estos bloques de código."],"metadata":{"id":"bAVepPPzjrVG"}},{"cell_type":"markdown","source":["<b>Captura del tipo de excepcio</b>"],"metadata":{"id":"-eKUU31qk4_k"}},{"cell_type":"code","source":["numberOne = 5\n","numberTwo = 1\n","numberTwo = '1'\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('No hay ningun error')\n","except TypeError as e: \n","  print(e)\n","\n","  #Asignamos el error ocurrido a una variable e imprmimos la información de nuestro error.\n","  #Esto funciona mayormente en VSCode, trabajando en Collab tenemos esta información desde el inicio"],"metadata":{"id":"sxWWMTiIk-NT","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1676296870517,"user_tz":360,"elapsed":188,"user":{"displayName":"Erick Galindo","userId":"17230836761258543942"}},"outputId":"421214ec-4dc5-4c3a-bd67-887f1e380a1b"},"execution_count":17,"outputs":[{"output_type":"stream","name":"stdout","text":["unsupported operand type(s) for +: 'int' and 'str'\n"]}]}]}